name: Deploy dev

on:
  push:
    branches: [ dev ]
    paths: 
      - 'dist/**'
  pull_request:
    branches: [ dev ]
    paths: 
      - 'dist/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          # ftp server
          server: ${{ secrets.ftp_server }}
          # ftp username
          username: ${{ secrets.ftp_username_test }}
          # ftp password
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
