name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          # ftp server
          server: ${{ secrets.ftp_server }}
          # ftp username
          username: ${{ secrets.ftp_username }}
          # ftp password
          password: ${{ secrets.ftp_password }}
          working-directory: ./dist
